# Generated by Django 2.1.5 on 2019-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20190209_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Question'),
        ),
    ]
